<?php

return [
    'A2A Energia' => 'A2A Energia',
    'Acea Energia' => 'Acea Energia',
    'AIM Energy' => 'AIM Energy',
    'Alperia Smart Services' => 'Alperia Smart Services',
    'Amg Gas' => 'Amg Gas',
    'Argos' => 'Argos',
    'Axpo Italia' => 'Axpo Italia',
    'Bluenergy Group' => 'Bluenergy Group',
    'CVA Energie' => 'CVA Energie',
    'Dolomiti Energia' => 'Dolomiti Energia',
    'Duferco Energia' => 'Duferco Energia',
    'Edison Energia' => 'Edison Energia',
    'Egea Commerciale' => 'Egea Commerciale',
    'Enegan' => 'Enegan',
    'Enercom' => 'Enercom',
    'Energit' => 'Energit',
    'Enerxenia' => 'Enerxenia',
    'Engie Italia' => 'Engie Italia',
    'Eni Plenitude' => 'Eni Plenitude',
    'Estra Energie' => 'Estra Energie',
    'Flyenergia' => 'Flyenergia',
    'Gesam Gas & Luce' => 'Gesam Gas & Luce',
    'Global Power' => 'Global Power',
    'Green Network Energy' => 'Green Network Energy',
    'Hera Comm' => 'Hera Comm',
    'Iberdrola Clienti Italia' => 'Iberdrola Clienti Italia',
    'Illumia' => 'Illumia',
    'Iren Mercato' => 'Iren Mercato',
    'Italgas Energia' => 'Italgas Energia',
    'Lifegate Energy' => 'Lifegate Energy',
    'Metamer' => 'Metamer',
    'NeN' => 'NeN',
    'NOVA AEG' => 'NOVA AEG',
    'NWG Energia' => 'NWG Energia',
    'Octopus Energy Italia' => 'Octopus Energy Italia',
    'Optima Italia' => 'Optima Italia',
    'Pulsee Luce e Gas' => 'Pulsee Luce e Gas',
    'Repower Vendita Italia' => 'Repower Vendita Italia',
    'Salerno Energia Vendite' => 'Salerno Energia Vendite',
    'SCM Energia' => 'SCM Energia',
    'Sorgenia' => 'Sorgenia',
    'Spigas Clienti' => 'Spigas Clienti',
    'Tate Energia' => 'Tate Energia',
    'Trenta' => 'Trenta',
    'UdBroker' => 'UdBroker',
    'Utilità' => 'Utilità',
    'VIVI energia' => 'VIVI energia',
    'Wekiwi' => 'Wekiwi',
];

